### ISSUE TITLE
PCB SPECS

### ISSUE THREAD

**Issue by guet-clg** [myriadrf/LimeSDR-XTRX#1]
Must IT-180A be used for PCB materials? Can I use FR4?

Must the ink be halogen-free, and can it be replaced by others?

**Comment by guet-clg** [comment]
Can you help me?

**Comment by ztamosevicius** [comment]
It is not mandatory to use IT-180A, any laminate which has a low loss tangent and a similar dielectric constant can be used. Plain FR4 is not the best option as the weave of the laminate and the loses might not be best suited for RF operation (especially in the 2 GHz and above region). In any case, if changing the material or thickness, controlled impedance trace widths might need to be tweaked for the target impedance (provided in the table in Mechanical 1 layer).

The ink type doesn't matter.

**Comment by guet-clg** [comment]
thank.！
